services:
    db:
        image: postgres
        container_name: pgsql

        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - POSTGRES_DB=pg
